# frozen_string_literal: true

# This file was generated by `bin/rails generate solid_queue:install`.
# It configures SolidQueue as the ActiveJob backend for reliable, database-backed job processing.

# For most apps, no further configuration is needed.
# For advanced options, see: https://github.com/basecamp/solid_queue#configuration

# SolidQueue automatically picks up the queue_adapter in each environment config.