# This migration was generated by `rails generate solid_queue:install`
class CreateSolidQueueTables < ActiveRecord::Migration[7.0]
  def change
    create_table :solid_queue_jobs do |t|
      t.string :queue_name, null: false
      t.string :job_class, null: false
      t.text :arguments, null: false
      t.integer :priority, null: false, default: 0
      t.datetime :scheduled_at
      t.datetime :finished_at
      t.datetime :discarded_at
      t.datetime :failed_at
      t.text :error
      t.timestamps
    end

    create_table :solid_queue_workers do |t|
      t.string :name, null: false
      t.datetime :last_heartbeat_at
      t.timestamps
    end

    create_table :solid_queue_executions do |t|
      t.references :job, null: false, foreign_key: { to_table: :solid_queue_jobs }
      t.references :worker, null: false, foreign_key: { to_table: :solid_queue_workers }
      t.datetime :started_at
      t.datetime :finished_at
      t.text :error
      t.timestamps
    end

    add_index :solid_queue_jobs, :queue_name
    add_index :solid_queue_jobs, :scheduled_at
    add_index :solid_queue_jobs, :finished_at
    add_index :solid_queue_jobs, :discarded_at
    add_index :solid_queue_jobs, :failed_at
  end
end